FROM n8nio/n8n:1.121.3

# --- Render variables ---
ENV N8N_PORT=${PORT}
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV N8N_SECURE_COOKIE=false
ENV EXECUTIONS_PROCESS=main
ENV N8N_RUNNERS_ENABLED=false

# --- Inform N8N about DB SSL ---
ENV DB_POSTGRES_SSL=true
ENV DB_TYPE=postgresdb

EXPOSE ${PORT}

CMD ["n8n"]
